// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace MT.UI.Tests.Usuario.Login
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class _2_LoginUsuarioFeature : Xunit.IClassFixture<_2_LoginUsuarioFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "LoginUsuario.feature"
#line hidden
        
        public _2_LoginUsuarioFeature()
        {
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "2 - Login Usuario", "\tUm Usuario fará login no site\r\n\tpreenchendo os campos necessários\r\n\tao terminar " +
                    "receberá uma notificacao \r\n\tde sucesso ou de falha ", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void SetFixture(_2_LoginUsuarioFeature.FixtureData fixtureData)
        {
        }
        
        void System.IDisposable.Dispose()
        {
            this.ScenarioTearDown();
        }
        
        [Xunit.FactAttribute(DisplayName="2_LoginUsuarioSucesso")]
        [Xunit.TraitAttribute("FeatureTitle", "2 - Login Usuario")]
        [Xunit.TraitAttribute("Description", "2_LoginUsuarioSucesso")]
        [Xunit.TraitAttribute("Category", "TesteAceitacaoLoginUsuario")]
        public virtual void _2_LoginUsuarioSucesso()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("2_LoginUsuarioSucesso", new string[] {
                        "TesteAceitacaoLoginUsuario"});
#line 9
this.ScenarioSetup(scenarioInfo);
#line 10
 testRunner.Given("que o usuario está no site, na pagina inicial", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 11
 testRunner.And("clica no link de login", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Campo",
                        "Valor"});
            table1.AddRow(new string[] {
                        "Email",
                        "leonardosimoura@gmail.com"});
            table1.AddRow(new string[] {
                        "Senha",
                        "Teste@123"});
#line 12
 testRunner.And("preenche os campos com os valores de login", ((string)(null)), table1, "E ");
#line 16
 testRunner.When("clicar no botao login", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 17
 testRunner.Then("Recebe uma mensagem com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line 18
 testRunner.Then("e eh direcionado para tela inicial", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                _2_LoginUsuarioFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                _2_LoginUsuarioFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
